### ISSUE TITLE
Install CoovaChilli 1.4 on Ubuntu 18.04

### ISSUE THREAD

**Issue by JeromeFitoussi** [coova/coova-chilli#454] opened 2018-09-30 12:57 UTC
Hello,

We use CoovaChilli for our company in France.
Unfortunately, since version 1.4 and Ubuntu 18.04, we cannot install it properly.

We are looking for someone who can help us install it (If possible in French language).
Even we are ready to pay for it.

Can someone help us?

Best regards,

Jerome

**Comment by heruan** [comment] 2018-09-30 15:52
Duplicate of https://github.com/coova/coova-chilli/issues/447.

**Comment by sevan** [comment] 2019-11-24 22:46
Please try v1.5 release and respond on #447 if you still have SSL issues.

**Closed by sevan** 2019-11-24 22:46 UTC
