### ISSUE TITLE
Configure nochallenge

### ISSUE THREAD

**Issue by tranvanhoa533** [coova/coova-chilli#528] opened 2021-08-24 15:50 UTC
I use coova 1.4 on openwrt 19.07.7. 

I try to configure nochallenge so I add the ```option nochallenge 1 ```  to file /etc/config/chilli.

I start coova with cmd: ```/etc/init.d/chilli start``` and always get an error.

```
Tue Aug 24 22:46:40 2021 daemon.debug chilli[3847]: (Re)processing options [/var/run/chilli.3847.cfg.bin]
Tue Aug 24 22:46:40 2021 daemon.err chilli[3847]: chilli[3847]: (Re)processing options [/var/run/chilli.3847.cfg.bin]
Tue Aug 24 22:46:40 2021 daemon.debug chilli[3849]: running chilli_opt on /var/run/chilli.3847.cfg.bin
Tue Aug 24 22:46:40 2021 daemon.err chilli[3847]: chilli[3849]: running chilli_opt on /var/run/chilli.3847.cfg.bin
Tue Aug 24 22:46:40 2021 daemon.err chilli[3847]: coova-chilli: option does not take an argument: nochallenge
Tue Aug 24 22:46:40 2021 daemon.warn chilli[3847]: could not generate configuration (/var/run/chilli.3847.cfg.bin), sleeping one second
Tue Aug 24 22:46:40 2021 daemon.err chilli[3847]: chilli[3847]: could not generate configuration (/var/run/chilli.3847.cfg.bin), sleeping one second
```

How can i configure nochallenge in openwrt.

Thank you.

**Comment by gmarsay** [comment] 2021-08-24 17:49
Hi @tranvanhoa533,

Maybe use value flag "on" for "nochallenge" option, not "1"

https://github.com/coova/coova-chilli/blob/06a8f1b6c1be2648d05509700f1e0f85b2088e61/src/cmdline.ggo#L239

**Comment by tranvanhoa533** [comment] 2021-08-25 00:50
Hi @gmarsay 

I tried configuring as you instructed: ```option nochallenge on```, but still getting the same error.

**Comment by nemesisdesign** [comment] 2022-07-08 23:15
It's a problem in the init.d script of the OpenWrt 19.07 package.

**Comment by tranvanhoa533** [comment] 2022-07-09 08:58
I added the flag nochallenge in cmd start in the init.d script and it
worked for me.

Thank you very much

Vào Th 7, 9 thg 7, 2022 vào lúc 06:15 Federico Capoano <
***@***.***> đã viết:

**Comment by nemesisdesign** [comment] 2022-07-16 00:26
@tranvanhoa533 please close this issue because this issue is not caused by coova-chilli but by the package on OpenWrt 19.07.

**Closed** 2022-07-16 13:49 UTC
